### ISSUE TITLE
Laravel - Queueing PushNotification gives Error (Serialization of 'Closure' is not allowed)

### ISSUE THREAD

**Issue by jandante** [pusher/push-notifications-php#32] opened 2020-10-11 18:32 UTC
Hi,

when using the PushNotifications SDK (importing from Pusher\PushNotifications\PushNotifications) I can send web notifications to users with this code in a function of a route:

    Route::get('test-notification', function() {
        $beamsClient = new PushNotifications(array(
            "instanceId" => env('PUSHER_BEAMS_INSTANCE_ID'),
            "secretKey" => env('PUSHER_BEAMS_SECRET_KEY')
        ));
    
        $publishId = $beamsClient->publishToUsers(
            array("user-3"),
            array(
                "web" => array(
                    "notification" => array(
                        "title" => "New information in the app available",
                        "body" => "go to the app for more infor...",
                        "icon" => "https://app.familyportal.be/img/icons/favicon-32x32.png",
                        "deep_link" => "https://localhost:8080/#/news"
                    )
                )
            )
        );
    });

However when I put the same code in a Job and call that job with the dispatch function I get an error: Serialization of 'Closure' is not allowed.

    <?php

    namespace App\Jobs;

    use Illuminate\Bus\Queueable;
    use Illuminate\Contracts\Queue\ShouldQueue;
    use Illuminate\Foundation\Bus\Dispatchable;
    use Illuminate\Queue\InteractsWithQueue;
    use Illuminate\Queue\SerializesModels;
    use Pusher\PushNotifications\PushNotifications;

    class SendNotification implements ShouldQueue
    {
        use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

        public $tries = 3;

        public $retryAfter = 450;

        public function __construct()
        {
            $this->beamsClient = new PushNotifications(array(
                "instanceId" => env('PUSHER_BEAMS_INSTANCE_ID'),
                "secretKey" => env('PUSHER_BEAMS_SECRET_KEY')
            ));
        }

        public function handle()
        {
            $this->beamsClient->publishToUsers(
                array("user-3"),
                array(
                    "web" => array(
                        "notification" => array(
                            "title" => "New information in the app available",
                            "body" => "go to the app for more infor...",
                            "icon" => "https://app.familyportal.be/img/icons/favicon-32x32.png",
                            "deep_link" => "https://localhost:8080/#/news"
                        )
                    )
                )
            );
        }
    }

Could be not totally related to this package (since it works in the first codeblock inside my routes/web.php') but I can't figure out why this is not working.

**Comment by ben-pusher** [comment] 2020-10-13 09:51
Hi. Looking at the code provided and the error message generated I don't believe this issue is specific to this library. The code you are using to trigger the notification is the same and as you say, it works in your routes/web.php file. 
It appears the issue you are encountering is caused by the way Laravel interacts with jobs/queues. It seems there are some suggestions from others who have encountered this issue, [for example ](https://laracasts.com/discuss/channels/lumen/pushing-a-job-to-the-queue-results-in-a-serialize-closure-error
)to not instantiate the client in the construct. 

I will close this issue as this forum is for reporting bugs with the library only. You should look to the laravel community for assistance in resolving this issue.

**Closed by ben-pusher** 2020-10-13 09:51 UTC

**Comment by jandante** [comment] 2020-10-25 14:27
@ben-pusher thanks for pointing me in the right direction! Instantiating the client in het construct was indeed a bad idea and has nothing to do with your package.
